import type { Metadata } from "next";
import "@/styles/globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/navbar/Navbar";

const mainRegular = localFont({
  variable: "--font-mainRegular",
  src: "../public/assets/fonts/OnService-Regular.woff2",
});

const mainMedium = localFont({
  variable: "--font-mainMedium",
  src: "../public/assets/fonts/OnService-Medium.woff2",
});

const mainSemiBold = localFont({
  variable: "--font-mainSemiBold",
  src: "../public/assets/fonts/OnService-SemiBold.woff2",
});

const mainBold = localFont({
  variable: "--font-mainBold",
  src: "../public/assets/fonts/OnService-Bold.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mainRegular.variable} ${mainMedium.variable} ${mainSemiBold.variable} ${mainBold.variable}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
